version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: microsoft/dotnet:2.0.4-sdk-2.1.3-jessie
    steps:
      - checkout
      - run:
          name: Where are we?
          command: pwd
      - run:
          name: LS
          command: ls
      - run:
          name: Enter the folder
          command: cd HelloConsole
      - run:
          name: Build
          command: dotnet build
